if {![package vsatisfies [package require Tcl] 8.4]} return
package ifneeded vc::rcs::parser           1.0 [list source [file join $dir rcsparser.tcl]]
package ifneeded vc::cvs::cmd              1.0 [list source [file join $dir cvs_cmd.tcl]]
package ifneeded vc::cvs::ws               1.0 [list source [file join $dir cvs.tcl]]
package ifneeded vc::fossil::cmd           1.0 [list source [file join $dir fossil_cmd.tcl]]
package ifneeded vc::fossil::ws            1.0 [list source [file join $dir fossil.tcl]]
package ifneeded vc::fossil::import::cvs   1.0 [list source [file join $dir importcvs.tcl]]
package ifneeded vc::fossil::import::stats 1.0 [list source [file join $dir import_statistics.tcl]]
package ifneeded vc::fossil::import::map   1.0 [list source [file join $dir import_map.tcl]]
package ifneeded vc::tools::log            1.0 [list source [file join $dir log.tcl]]
